name: HGKits
version: 1.2.1
main: me.technopvp.hgkits.HGKits
author: tpvp
description: Hunger games kits.

commands:
    drop:
        aliases: [dropitem]
        usage: /<command>
        description: Drops the players current item.
    hgkits:
        aliases: [plugin, hgk]
        usage: /<command>
        description: Get's the plugins commands.
    kits:
        aliases: [listkits, kitlist]
        usage: /<command>
        description: List's all the kits from the configeration file.
    kit:
        aliases: [getkit]
        usage: /<command>
        description: Kit commands such as creating, removing, and getting.
    stats:
    duel:
    setstats:
        
permissions:
    hgkits.pvp:
         description: Kit pvp
         default: op
    hgkits.owner:
         description: Global permission for owner.
         default: op
    hgkits.admin:
         description: Global permission for admin.
         default: op
    hgkits.mod:
         description: Global permission for mod.
         default: op
    hgkits.trial:
         description: Global permission for trial.
         default: op
    hgkits.donor:
         description: Global permission for donor.
         default: op
